org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dcom.android.tools.r8.threadCount=1
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false

kotlin.code.style=official
ksp.incremental=true
